name: renovate-config-validator

on:
  push:
    paths:
      - .github/**
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: suzuki-shunsuke/github-action-renovate-config-validator@v1.1.1
